language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t shekharkumar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shekharkumar/docker-react npm run test -- --coverage

















    